// Code generated by tools/register.go DO NOT EDIT.
package events

import (
	"spyal/contracts"
	)


const (
	Echoevent contracts.EventName = iota
	Testevent contracts.EventName = iota
	EventNameCount
)

func GetEventName(e contracts.EventName) string {
	switch e {
	case Echoevent:
		return "Echoevent"
	case Testevent:
		return "Testevent"
	case EventNameCount:
		return "Count"
	default:
		return "Unknown"
	}
}
