// Code generated by tools/register.go DO NOT EDIT.
package events

import (
	"spyal/contracts"
	)


const (
	Baseevent contracts.EventName = iota
	Echoevent contracts.EventName = iota
	EventNameCount
)

func GetEventName(e contracts.EventName) string {
	switch e {
	case Baseevent:
		return "Baseevent"
	case Echoevent:
		return "Echoevent"
	case EventNameCount:
		return "Count"
	default:
		return "Unknown"
	}
}
