// Code generated by tools/register.go DO NOT EDIT.
package events

import (
	"spyal/contracts"
)


// constants
const (
    Baseevent contracts.EventName = iota
    Echoevent contracts.EventName = iota
    EventNameCount
)

// NewEvent returns the constructor of the event by its EventName
func NewEvent(name contracts.EventName, data map[string]any) contracts.Event {
	switch name {
	case Baseevent:
		return NewBaseEvent(data)
	case Echoevent:
		return NewEchoEvent(data)
	default:
		return nil
	}
}
