// Code generated by tools/register.go DO NOT EDIT.
package channels

import (
	"spyal/contracts"
)

//nolint:gochecknoglobals
var Channels = map[string]contracts.Channel{
    "default": NewDefaultChannel(),
    "echo": NewEchoChannel(),
    "game": NewGameChannel(),
}
