// Code generated by tools/register.go DO NOT EDIT.
package listeners

import "spyal/contracts"

var ListenerRegistry = []contracts.NewListenerFunc {
	NewChatListener,
	NewEchoListener,
	NewGameEndListener,
	NewGameListener,
	NewLeftListener,
	NewUserJoinedListener,
}
