// Code generated by tools/register.go DO NOT EDIT.

export enum EventName {
    Baseevent = 0,
    Chatevent = 1,
    Echoevent = 2,
    Gameendevent = 3,
    Gameevent = 4,
    Leftevent = 5,
    Userjoinedevent = 6,
    EventNameCount = 7
}

export type EventData = { [key: string]: any };

export interface Event {
    name: EventName;
    data: EventData;
}
