// Code generated by tools/register.go DO NOT EDIT.

export enum EventName {
    Baseevent = 0,
    Echoevent = 1,
    Gameevent = 2,
    Userjoinedevent = 3,
    EventNameCount = 4
}

export type EventData = { [key: string]: any };

export interface Event {
    name: EventName;
    data: EventData;
}
